name: flutter_meta_wearables_dat
description: "Flutter bridge to Meta's Wearables DAT for iOS and Android."
version: 0.3.0
repository: https://github.com/rodcone/flutter_meta_wearables_dat

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.rodcone.flutter_meta_wearables_dat
        pluginClass: MetaWearablesDatPlugin
      ios:
        pluginClass: MetaWearablesDatPlugin