// Generated by Apple Swift version 6.3.3 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef MWDATMOCKDEVICE_SWIFT_H
#define MWDATMOCKDEVICE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATMockDevice",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#elif defined(__OBJC__)
#import <objc/objc-exception.h>
#import <objc/NSObjCRuntime.h>
#import <objc/objc-sync.h>
#import <objc/message.h>
#import <objc/objc.h>
#import <objc/runtime.h>
#import <objc/NSObject.h>
#import <objc/objc-auto.h>
#import <objc/objc-api.h>
#else
#include <objc/objc-exception.h>
#include <objc/NSObjCRuntime.h>
#include <objc/objc-sync.h>
#include <objc/message.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#include <objc/NSObject.h>
#include <objc/objc-auto.h>
#include <objc/objc-api.h>
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATMockDevice",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// A named hardware button.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATButtonType, "ObjC_ButtonType", closed) {
/// The primary action button.
  MWDATButtonTypeAction = 0,
/// Not a button event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>button</code>.
  MWDATButtonTypeUnknown = 1,
};

/// The kind of capture interaction.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATCapturePressType, "ObjC_CapturePressType", closed) {
/// A single short press of the capture button. Defaults to capturing a photo.
  MWDATCapturePressTypeShortPress = 0,
/// A press and hold of the capture button. Defaults to starting a video recording.
  MWDATCapturePressTypeHold = 1,
/// A double press of the capture button. Defaults to stopping an in-progress video recording.
  MWDATCapturePressTypeDoublePress = 2,
/// Not a capture event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>capture</code>.
  MWDATCapturePressTypeUnknown = 3,
};

/// The phase of a drag interaction.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDragAction, "ObjC_DragAction", closed) {
/// The pointer went down, beginning the drag.
  MWDATDragActionDown = 0,
/// The pointer moved while down.
  MWDATDragActionMove = 1,
/// The pointer went up, ending the drag.
  MWDATDragActionUp = 2,
/// Not a drag event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>drag</code>.
  MWDATDragActionUnknown = 3,
};

/// The device surface that produced an input event.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATInputSource, "ObjC_InputSource", closed) {
/// The capacitive touchpad on the glasses.
  MWDATInputSourceCaptouch = 0,
/// Neural Band discrete gesture input.
  MWDATInputSourceNeuralBand = 1,
/// The dedicated capture button on the glasses.
  MWDATInputSourceCaptureButton = 2,
/// The dedicated action button on the glasses.
  MWDATInputSourceActionButton = 3,
/// Neural Band pinch-and-drag input.
  MWDATInputSourceNeuralBandDrag = 4,
/// The source could not be determined.
  MWDATInputSourceUnknown = 5,
};

@class NSURL;
/// Objective-C bridge for configuring standalone photo capture on simulated glasses.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_MockCameraCaptureKit")
@interface MockCameraCaptureKit : NSObject
/// Set the image file to return when a photo capture is triggered.
/// \param fileURL URL of the file containing the image (JPEG or HEIC).
///
- (void)setCapturedPhotoWithFileURL:(NSURL * _Nonnull)fileURL;
/// Simulate a capture failure on the next capture attempt.
- (void)simulateCaptureFailure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("ObjC_MockCameraKit")
@interface MockCameraKit : NSObject
/// Set camera feed from a video file. Supported codecs: h.265
/// \param fileURL URL of the file containing video stream
///
- (void)setCameraFeedWithFileURL:(NSURL * _Nonnull)fileURL;
/// Set the camera source to stream live from the phone’s camera.
/// \param cameraFacing 0 for front camera, 1 for back camera.
///
- (void)setCameraFeedWithCameraFacing:(NSInteger)cameraFacing;
/// Set captured image from an image file.
/// \param fileURL URL of the file containing image
///
- (void)setCapturedImageWithFileURL:(NSURL * _Nonnull)fileURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("ObjC_MockCaptouchKit")
@interface MockCaptouchKit : NSObject
/// Simulate a single tap gesture on the device’s capacitive touch sensor.
- (void)tap;
/// Simulate a tap-and-hold gesture that stops the active session.
- (void)tapAndHold;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
SWIFT_PROTOCOL_NAMED("ObjC_MockDevice")
@protocol MockDevice
/// Returns the device identifier
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceIdentifier;
/// Powers on the mock device.
- (void)powerOn;
/// Powers off the mock device.
- (void)powerOff;
/// Simulates putting on (donning) the device.
- (void)don;
/// Simulates taking off (doffing) the device.
- (void)doff;
@end

@protocol MockGlasses;
SWIFT_CLASS_NAMED("ObjC_MockDeviceKit")
@interface MWDATMockDeviceKit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MWDATMockDeviceKit * _Nonnull sharedInstance;)
+ (MWDATMockDeviceKit * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Whether MockDeviceKit is currently enabled.
@property (nonatomic, readonly) BOOL isEnabled;
/// Enables MockDeviceKit with the default configuration (initially registered).
- (void)enable;
/// Enables MockDeviceKit with the specified initial registration state.
/// \param initiallyRegistered When <code>true</code>, enables in <code>.registered</code> state.
/// When <code>false</code>, enables in <code>.unavailable</code> state, allowing <code>startRegistration()</code> to be tested.
///
- (void)enableWithInitiallyRegistered:(BOOL)initiallyRegistered;
/// Disables MockDeviceKit and unpairs all devices.
- (void)disable;
/// All paired devices.
@property (nonatomic, readonly, copy) NSArray<id <MockDevice>> * _Nonnull pairedDevices;
/// Pairs a simulated glasses device of the specified model.
/// \param modelRawValue Raw string value of <code>GlassesModel</code> (e.g. <code>"Ray-Ban Meta"</code>).
///
///
/// returns:
/// A mock glasses device, or <code>nil</code> if the model is invalid or MockDeviceKit is not enabled.
- (id <MockGlasses> _Nullable)pairGlassesWithModelRawValue:(NSString * _Nonnull)modelRawValue SWIFT_WARN_UNUSED_RESULT;
/// Unpair simulated device
- (void)unpairDevice:(id <MockDevice> _Nonnull)device;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
SWIFT_CLASS_NAMED("ObjC_MockDisplayKit")
@interface MockDisplayKit : NSObject
/// Sends a display click for the supplied element identifier.
///
/// returns:
/// Whether the click was delivered to an active DISPLAY capability.
- (BOOL)sendClickWithIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT;
/// Creates a locally rendered preview of the captured display content. The returned view is
/// single-use; create a new view after removing it from its superview.
- (UIView * _Nonnull)createPreviewView SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MockGlassesServices;
SWIFT_PROTOCOL_NAMED("ObjC_MockGlasses")
@protocol MockGlasses <MockDevice>
/// Simulates folding the glasses into a closed position.
- (void)fold;
/// Simulates unfolding the glasses into an open position.
- (void)unfold;
/// Container for accessing mock device service kits (camera, voice invocation, etc.).
@property (nonatomic, readonly, strong) MockGlassesServices * _Nonnull services;
@end

@class MockSpeechKit;
@class MockMotionKit;
@class MockInputKit;
@class MockVoiceInvocationKit;
SWIFT_CLASS_NAMED("ObjC_MockGlassesServices")
@interface MockGlassesServices : NSObject
@property (nonatomic, readonly, strong) MockCameraKit * _Nonnull camera;
@property (nonatomic, readonly, strong) MockCaptouchKit * _Nonnull captouch;
/// Configures standalone photo capture behavior for the simulated glasses.
/// @Unpublishable
@property (nonatomic, readonly, strong) MockCameraCaptureKit * _Nonnull cameraCapture;
/// Injects synthetic Speech capability events.
/// @Unpublishable
@property (nonatomic, readonly, strong) MockSpeechKit * _Nonnull speech;
/// Injects deterministic Motion samples.
/// @Unpublishable
@property (nonatomic, readonly, strong) MockMotionKit * _Nonnull motion;
/// Injects synthetic Inputs capability events.
/// @Unpublishable
@property (nonatomic, readonly, strong) MockInputKit * _Nonnull input;
@property (nonatomic, readonly, strong) MockDisplayKit * _Nonnull display;
@property (nonatomic, readonly, strong) MockVoiceInvocationKit * _Nonnull voiceInvocation;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Injects synthetic input interactions into a connected app during testing. Objective-C mirror of
/// <code>MockInputKit</code>.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_MockInputKit")
@interface MockInputKit : NSObject
/// Injects an upward navigation event from the given source.
- (void)navUpWithSource:(enum MWDATInputSource)source;
/// Injects a downward navigation event from the given source.
- (void)navDownWithSource:(enum MWDATInputSource)source;
/// Injects a leftward navigation event from the given source.
- (void)navLeftWithSource:(enum MWDATInputSource)source;
/// Injects a rightward navigation event from the given source.
- (void)navRightWithSource:(enum MWDATInputSource)source;
/// Injects a select / confirm event from the given source.
- (void)selectWithSource:(enum MWDATInputSource)source;
/// Injects a back / dismiss event from the given source.
- (void)backWithSource:(enum MWDATInputSource)source;
/// Injects a capture-button press resolved to the given press type.
- (void)captureWithPressType:(enum MWDATCapturePressType)pressType;
/// Injects a physical button press.
- (void)buttonWithType:(enum MWDATButtonType)type;
/// Injects one sample of a continuous Neural Band drag stream.
- (void)dragWithAction:(enum MWDATDragAction)action x:(float)x y:(float)y dx:(float)dx dy:(float)dy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Keep in sync with the <code>MockMotionKit</code> Swift protocol.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_MockMotionKit")
@interface MockMotionKit : NSObject
@property (nonatomic, readonly) BOOL isStreaming;
/// Feed a CSV recording for deterministic replay; the in-memory <code>[MotionSample]</code> overload is Swift-only.
- (void)setMotionFeedWithFileURL:(NSURL * _Nonnull)fileURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Controls synthetic Speech events for a mock device.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_MockSpeechKit")
@interface MockSpeechKit : NSObject
@property (nonatomic, readonly) BOOL isListening;
/// <code>MockSpeechSource</code> is a Swift enum that cannot cross to ObjC, so it is exposed as a Bool.
/// Only takes effect while not <code>isListening</code>.
- (void)setLiveDeviceAsrEnabled:(BOOL)enabled;
- (void)simulateTranscriptionWithText:(NSString * _Nonnull)text isFinal:(BOOL)isFinal confidence:(float)confidence;
- (void)simulateErrorWithErrorCode:(int32_t)errorCode message:(NSString * _Nonnull)message;
- (void)simulateCompletion;
- (void)setLocale:(NSString * _Nonnull)locale;
/// Snapshot only — the Swift <code>liveSourceDiagnosticPublisher</code> (<code>Announcer</code>) cannot cross to ObjC.
@property (nonatomic, readonly, copy) NSString * _Nullable liveSourceDiagnostic;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("ObjC_MockVoiceInvocationKit")
@interface MockVoiceInvocationKit : NSObject
/// Sends a launch app action to all connected clients.
///
/// returns:
/// The request ID of the sent action, or nil if no clients are connected.
- (NSString * _Nullable)sendLaunchAppAction SWIFT_WARN_UNUSED_RESULT;
/// Sends a deliberately malformed action to all connected clients.
///
/// returns:
/// The request ID of the sent action, or nil if no clients are connected.
- (NSString * _Nullable)sendIncompleteAction SWIFT_WARN_UNUSED_RESULT;
/// Returns true if there are connected clients.
@property (nonatomic, readonly) BOOL hasConnectedClients;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
